/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/_index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMessegesRouteImport } from './routes/_app.messeges'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppConnectionsRouteImport } from './routes/_app.connections'

const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessegesRoute = AppMessegesRouteImport.update({
  id: '/messeges',
  path: '/messeges',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof AppConnectionsRoute
  '/feed': typeof AppFeedRoute
  '/messeges': typeof AppMessegesRoute
  '/notifications': typeof AppNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof AppConnectionsRoute
  '/feed': typeof AppFeedRoute
  '/messeges': typeof AppMessegesRoute
  '/notifications': typeof AppNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_index': typeof IndexRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/messeges': typeof AppMessegesRoute
  '/_app/notifications': typeof AppNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connections' | '/feed' | '/messeges' | '/notifications'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connections' | '/feed' | '/messeges' | '/notifications'
  id:
    | '__root__'
    | '/_app'
    | '/_index'
    | '/_app/connections'
    | '/_app/feed'
    | '/_app/messeges'
    | '/_app/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messeges': {
      id: '/_app/messeges'
      path: '/messeges'
      fullPath: '/messeges'
      preLoaderRoute: typeof AppMessegesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppFeedRoute: typeof AppFeedRoute
  AppMessegesRoute: typeof AppMessegesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectionsRoute: AppConnectionsRoute,
  AppFeedRoute: AppFeedRoute,
  AppMessegesRoute: AppMessegesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
